import Head from 'next/head'
import { FC } from 'react'

interface PageTitleProps {
    title: string
}

const PageTitle: FC<PageTitleProps> = (props) => {
    const pageTitle: string = `${props.title} | Springbook`
    return (
        <Head>
            <title>{pageTitle}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default PageTitle